# Generated by Django 5.1.2 on 2024-10-25 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0016_alter_booking_total_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='license_plate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 0, 0)),
        ),
    ]
